version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-challenge-kafka-1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-challenge-kafka-1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

    ports:
      - 9092:9092
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka-challenge-zookeeper-1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

    ports:
      - 2181:2181
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
